### ISSUE TITLE
Using libzip in external c++ project

### ISSUE THREAD

**Issue by jakobloeg** [kiyolee/zlib-win-build#1]
Hi, 

I am trying to make use of this very nice project in my own c++ source code (that uses CMake). I did as follows: 

1. Downloaded zlib and libzip projects
2. Compiled libzip-static succesfully into libzip-static.lib file
3. Made a folder c:/local/mylib/include with header files from the libzip project
4. Made a folder c:/local/mylib/lib with the libzip-static.lib file
5. Set "LIBZIP_LIBRARY" and "LIBZIP_INCLUDE_DIR" in CMakeLists.txt accordingly 
6. When i compile i receive a lot of linker errors such as "error LNK2019: unresolved external symbol deflate referenced in function compress_read "

Can you help me with what I am doing wrong?

**Comment by kiyolee** [comment]
You need to link to libz-static.lib as well.
Regards,
Kelvin

Sent from Mail for Windows 10

From: jakobloeg
Sent: Thursday, 7 December 2017 9:58 PM
To: kiyolee/zlib-win-build
Cc: Subscribed
Subject: [kiyolee/zlib-win-build] Using libzip in external c++ project (#1)

Hi,
I am trying to make use of this very nice project in my own c++ source code (that uses CMake). I did as follows:
1. Downloaded zlib and libzip projects
2. Compiled libzip-static succesfully into libzip-static.lib file
3. Made a folder c:/local/mylib/include with header files from the libzip project
4. Made a folder c:/local/mylib/lib with the libzip-static.lib file
5. Set "LIBZIP_LIBRARY" and "LIBZIP_INCLUDE_DIR" in CMakeLists.txt accordingly
6. When i compile i receive a lot of linker errors such as "error LNK2019: unresolved external symbol deflate referenced in function compress_read "
Can you help me with what I am doing wrong?

**Comment by kiyolee** [comment]
Updated README for libzip and hope that it is clearer now.
