### ISSUE TITLE
Using libzip and manipulate the code

### ISSUE THREAD

**Issue by luca2125** [kiyolee/zlib-win-build#2]
Hi,

I have compiled zlib in vs2017 and work without errors.

Tested to an external app and work fine.

I need to find the entry point of dll (that general is "DllMain") but I don't found it.

Can you please tell me where I can found the  entry point of dll in tris project ?

Thanks !

**Comment by kiyolee** [comment]
DllMain() is optional and both zlib and libzip do not need one.

**Comment by luca2125** [comment]
thank you. If for example I need it for "zlib" in what file and position can be inserted to work fine ?

I'am new in c and I have not undestand where the program begin. I need it to hook a game to implement a new feature.

Thanks !

**Comment by kiyolee** [comment]
It depends on how complicate the code you are going to add.
If it is simple, you may add DllMain() to zutil.c that seems to contain miscellaneous stuff.
Or you may add new files but that way you need to change the projects files. That may complicate future git merges.
If you are new to C programming, I'd suggest you to try both methods and get some ideas about the differences.
That will help you make better decision for future projects.

N.B. Reminded here is not general C programming forum. Please post general C programming questions elsewhere, stackoverflow.com is a better place I suppose.
