### ISSUE TITLE
No zlib release including VS2019

### ISSUE THREAD

**Issue by LarsKloseLke** [kiyolee/zlib-win-build#3]
I just tried to make a libxslt-win-build with VS2019, therefore needed to build zlib-win-build first.
It seems a release including the VS2019 solution is missing right now. I'll manage by using master but it would be nice to have consistent releases available for all dependencies of libxslt-win-build.

**Comment by kiyolee** [comment]
Ah, I lost track that the last proper release was only up to VS2017. Perhaps I should release a new one to cover all the later improvement eventhough zlib itself has not been changed a bit.
Thanks for reminding me that.

**Comment by kiyolee** [comment]
Please check the latest release zlib-1.2.11-p3-win-build.
