### ISSUE TITLE
VS 2019 - zlib outputs "libz-static.lib"

### ISSUE THREAD

**Issue by bferguson3** [kiyolee/zlib-win-build#5]
Just to avoid confusion with libz. :)

**Comment by kiyolee** [comment]
not sure what you meant.

**Comment by bferguson3** [comment]
The output should be named "zlib" not "libz". libz is for libzip.

**Comment by kiyolee** [comment]
That's intentional. I like lib name follow dll name. I produce libz.dll here to follow convention having "lib" as prefix like most unices.
If you prefer zlib.dll, you need to use official zlib build.
Btw, libzip produces libzip.dll and libzip.lib and so on.
