### ISSUE TITLE
Enabled Enhanced Instruction Set

### ISSUE THREAD

**Issue by MichaRotstein** [kiyolee/zlib-win-build#6]
Thank you for providing this build.

The default for "Enabled Enhanced Instruction Set" (under "Code Generation") is set to "Advanced Vector Extensions 2 (X86/X64) (/arch:AVX2)"

This his caused Zlib to crash our server on some of the machines we deployed it to and took a long time to find.

I suggest changing the default to "Not Set", if needed a different configuration can be used to compile to processors that support AVX2.

**Comment by kiyolee** [comment]
Is this still a problem? I thought nobody would still be using CPUs that old without AVX2.

**Comment by kofifus** [comment]
It was a problem for us on a few deployed sites which had old HW

**Comment by kiyolee** [comment]
I am OK to rollback that change. I will do that later today.

**Comment by kiyolee** [comment]
I have rolled back the AVX/AVX2 changes.
